spreadsheet_id: "1FyxFcgJ9pOqalE_k21bXGJggzSpZpcILw6Lb1_1WHkQ"
semester_tag:
  alias: spring26
  name: Spring 2026
  type: semester
distribution_spreadsheet_id: "1MFul8dgrKydjxzOHkAFH27qlf3uCCPEdgdTa2-lY0AA"
targets:
- sheet_name: "BS2 RU"
- sheet_name: "BS3 Tech"
save_ics_path: spring26/electives
save_json_path: spring26/electives.json
electives: [
    # En programs
    {
      "alias": "spring26-bs3-tech-spda",
      "short_name": "SPDA",
      "name": "Software Product Development and Analysis",
      "instructor": "Konstantin Arkhipov",
    },
    {
      "alias": "spring26-bs3-tech-idso",
      "short_name": "IDSO",
      "name": "Introduction to DevSecOps",
      "instructor": "Dmitry Creed",
    },
    {
      "alias": "spring26-bs3-tech-ido",
      "short_name": "IDO",
      "name": "Introduction to DevOps",
      "instructor": "Dmitry Creed",
    },
    {
      "alias": "spring26-bs3-tech-aih",
      "short_name": "AIH",
      "name": "Artificial Intelligence in Healthcare",
      "instructor": "Gcinizwe Dlamini",
    },
    {
      "alias": "spring26-bs3-tech-bait",
      "short_name": "BA",
      "name": "Business Analysis in IT",
      "instructor": "Ivan Goskov",
    },
    {
      "alias": "spring26-bs3-tech-atit",
      "short_name": "ATC",
      "name": "Advanced Technical Communications in IT",
      "instructor": "Ekateryna Ushakova",
    },
    # Ru programs
    {
      "alias": "spring26-rus-bs2-ввтус",
      "short_name": "ВВТУС",
      "name": "Введение в теорию управляемых систем",
      "instructor": "Sergei Savin",
    },
    {
      "alias": "spring26-rus-bs2-мокв",
      "short_name": "МОКВ",
      "name": "Математические основы квантовых вычислений",
      "instructor": "Oleg Kiselev, Mikhail Moshchanetskii",
    },
    {
      "alias": "spring26-rus-bs2-оскм",
      "short_name": "ОСКВМ",  # TODO: Change to 'ОСКМ' once it's fixed in the table
      "name": "Основы математического и компьютерного моделирования",
      "instructor": "Anna Maslovskaya",
    },
    {
      "alias": "spring26-rus-bs2-пмирв",
      "short_name": "ПМИРВ",
      "name": "Прикладная математика: искусство и ремесло вычислений (углубленный курс)",
      "instructor": "Gordin Vladimir, Smirnov Mikhail",
    },
    {
      "alias": "spring26-rus-bs2-фа",
      "short_name": "ФА",
      "name": "Функциональный анализ",
      "instructor": "Ostanin Pavel. Butakov Ivan",
    },
    {
      "alias": "spring26-rus-bs2-виапрпо",
      "short_name": "ВИАПР",
      "name": "Введение в интеграцию и автоматизацию процесса разработки ПО",
      "instructor": "Dmitry Creed",
    },
    {
      "alias": "spring26-rus-bs2-фа",
      "short_name": "ФА",
      "name": "Функциональный анализ",
      "instructor": "Ostanin Pavel. Butakov Ivan",
    },
    {
      "alias": "spring26-rus-bs2-высвыч",
      "short_name": "ВВ",
      "name": "Высокопроизводительные вычисления",
      "instructor": "Ivan Konyukhov",
    },
    {
      "alias": "spring26-rus-bs2-оснр",
      "short_name": "ОР",
      "name": "Основы робототехники",
      "instructor": "Alexandr Maloletov",
    },
    {
      "alias": "spring26-rus-bs2-углп",
      "short_name": "УPy",
      "name": "Углубленный Python",
      "instructor": "Быков Кирилл Валерьевич",
    },
]
